// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/userService.proto

package userService

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for UserService service

type UserService interface {
	GetTableUserList(ctx context.Context, in *Req, opts ...client.CallOption) (*UserListRsp, error)
	GetTableUserByUsername(ctx context.Context, in *UsernameReq, opts ...client.CallOption) (*UserRsp, error)
	GetTableUserById(ctx context.Context, in *IdReq, opts ...client.CallOption) (*UserRsp, error)
	InsertTableUser(ctx context.Context, in *UserReq, opts ...client.CallOption) (*BoolRsp, error)
	GetFeedUserById(ctx context.Context, in *IdReq, opts ...client.CallOption) (*FeedUserRsp, error)
	GetFeedUserByIdWithCurId(ctx context.Context, in *CurIdReq, opts ...client.CallOption) (*FeedUserRsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetTableUserList(ctx context.Context, in *Req, opts ...client.CallOption) (*UserListRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetTableUserList", in)
	out := new(UserListRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetTableUserByUsername(ctx context.Context, in *UsernameReq, opts ...client.CallOption) (*UserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetTableUserByUsername", in)
	out := new(UserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetTableUserById(ctx context.Context, in *IdReq, opts ...client.CallOption) (*UserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetTableUserById", in)
	out := new(UserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) InsertTableUser(ctx context.Context, in *UserReq, opts ...client.CallOption) (*BoolRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.InsertTableUser", in)
	out := new(BoolRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetFeedUserById(ctx context.Context, in *IdReq, opts ...client.CallOption) (*FeedUserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetFeedUserById", in)
	out := new(FeedUserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetFeedUserByIdWithCurId(ctx context.Context, in *CurIdReq, opts ...client.CallOption) (*FeedUserRsp, error) {
	req := c.c.NewRequest(c.name, "UserService.GetFeedUserByIdWithCurId", in)
	out := new(FeedUserRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	GetTableUserList(context.Context, *Req, *UserListRsp) error
	GetTableUserByUsername(context.Context, *UsernameReq, *UserRsp) error
	GetTableUserById(context.Context, *IdReq, *UserRsp) error
	InsertTableUser(context.Context, *UserReq, *BoolRsp) error
	GetFeedUserById(context.Context, *IdReq, *FeedUserRsp) error
	GetFeedUserByIdWithCurId(context.Context, *CurIdReq, *FeedUserRsp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		GetTableUserList(ctx context.Context, in *Req, out *UserListRsp) error
		GetTableUserByUsername(ctx context.Context, in *UsernameReq, out *UserRsp) error
		GetTableUserById(ctx context.Context, in *IdReq, out *UserRsp) error
		InsertTableUser(ctx context.Context, in *UserReq, out *BoolRsp) error
		GetFeedUserById(ctx context.Context, in *IdReq, out *FeedUserRsp) error
		GetFeedUserByIdWithCurId(ctx context.Context, in *CurIdReq, out *FeedUserRsp) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) GetTableUserList(ctx context.Context, in *Req, out *UserListRsp) error {
	return h.UserServiceHandler.GetTableUserList(ctx, in, out)
}

func (h *userServiceHandler) GetTableUserByUsername(ctx context.Context, in *UsernameReq, out *UserRsp) error {
	return h.UserServiceHandler.GetTableUserByUsername(ctx, in, out)
}

func (h *userServiceHandler) GetTableUserById(ctx context.Context, in *IdReq, out *UserRsp) error {
	return h.UserServiceHandler.GetTableUserById(ctx, in, out)
}

func (h *userServiceHandler) InsertTableUser(ctx context.Context, in *UserReq, out *BoolRsp) error {
	return h.UserServiceHandler.InsertTableUser(ctx, in, out)
}

func (h *userServiceHandler) GetFeedUserById(ctx context.Context, in *IdReq, out *FeedUserRsp) error {
	return h.UserServiceHandler.GetFeedUserById(ctx, in, out)
}

func (h *userServiceHandler) GetFeedUserByIdWithCurId(ctx context.Context, in *CurIdReq, out *FeedUserRsp) error {
	return h.UserServiceHandler.GetFeedUserByIdWithCurId(ctx, in, out)
}
