// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/commentService.proto

package commentService

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CommentService service

func NewCommentServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CommentService service

type CommentService interface {
	CountFromVideoId(ctx context.Context, in *IdReq, opts ...client.CallOption) (*CountRsp, error)
	Send(ctx context.Context, in *CommentReq, opts ...client.CallOption) (*CommentRsp, error)
	Delete(ctx context.Context, in *IdReq, opts ...client.CallOption) (*DelRsp, error)
	GetList(ctx context.Context, in *VideoUserReq, opts ...client.CallOption) (*CommentListRsp, error)
}

type commentService struct {
	c    client.Client
	name string
}

func NewCommentService(name string, c client.Client) CommentService {
	return &commentService{
		c:    c,
		name: name,
	}
}

func (c *commentService) CountFromVideoId(ctx context.Context, in *IdReq, opts ...client.CallOption) (*CountRsp, error) {
	req := c.c.NewRequest(c.name, "CommentService.CountFromVideoId", in)
	out := new(CountRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentService) Send(ctx context.Context, in *CommentReq, opts ...client.CallOption) (*CommentRsp, error) {
	req := c.c.NewRequest(c.name, "CommentService.Send", in)
	out := new(CommentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentService) Delete(ctx context.Context, in *IdReq, opts ...client.CallOption) (*DelRsp, error) {
	req := c.c.NewRequest(c.name, "CommentService.Delete", in)
	out := new(DelRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentService) GetList(ctx context.Context, in *VideoUserReq, opts ...client.CallOption) (*CommentListRsp, error) {
	req := c.c.NewRequest(c.name, "CommentService.GetList", in)
	out := new(CommentListRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CommentService service

type CommentServiceHandler interface {
	CountFromVideoId(context.Context, *IdReq, *CountRsp) error
	Send(context.Context, *CommentReq, *CommentRsp) error
	Delete(context.Context, *IdReq, *DelRsp) error
	GetList(context.Context, *VideoUserReq, *CommentListRsp) error
}

func RegisterCommentServiceHandler(s server.Server, hdlr CommentServiceHandler, opts ...server.HandlerOption) error {
	type commentService interface {
		CountFromVideoId(ctx context.Context, in *IdReq, out *CountRsp) error
		Send(ctx context.Context, in *CommentReq, out *CommentRsp) error
		Delete(ctx context.Context, in *IdReq, out *DelRsp) error
		GetList(ctx context.Context, in *VideoUserReq, out *CommentListRsp) error
	}
	type CommentService struct {
		commentService
	}
	h := &commentServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CommentService{h}, opts...))
}

type commentServiceHandler struct {
	CommentServiceHandler
}

func (h *commentServiceHandler) CountFromVideoId(ctx context.Context, in *IdReq, out *CountRsp) error {
	return h.CommentServiceHandler.CountFromVideoId(ctx, in, out)
}

func (h *commentServiceHandler) Send(ctx context.Context, in *CommentReq, out *CommentRsp) error {
	return h.CommentServiceHandler.Send(ctx, in, out)
}

func (h *commentServiceHandler) Delete(ctx context.Context, in *IdReq, out *DelRsp) error {
	return h.CommentServiceHandler.Delete(ctx, in, out)
}

func (h *commentServiceHandler) GetList(ctx context.Context, in *VideoUserReq, out *CommentListRsp) error {
	return h.CommentServiceHandler.GetList(ctx, in, out)
}
